### ISSUE TITLE
Feature: Allow to include more information besides the message

### ISSUE THREAD

**Issue by nicolaslara** [bartTC/django-eventlog#1]
We may want to display more information besides a simple message. Maybe even a traceback?

**Comment by bartTC** [comment]
Yeah, I was thinking of adding a JSONField to the event model and then .. do what you want, as long as its serializable. Then display the JSON somewhat formatted in the admin.

**Comment by bartTC** [comment]
Haven't had the need for this in a while now so I'm closing it until there's' again.

**Comment by bartTC** [comment]
A JSONField has been added in v1.5.
